Repository openwisp/django-rest-framework-gis, pull requests merged in 2020-08, with the labels that each got.

#226 Implement DistanceToPointOrderingFilter
  README.rst
  rest_framework_gis/filters.py
  tests/django_restframework_gis_tests/test_filters.py
  tests/django_restframework_gis_tests/urls.py
  tests/django_restframework_gis_tests/views.py
Labels: enhancement, feature-request

#232 [deps] Add support for django 3.1 in travis testing #227
  tox.ini
Labels: enhancement

#233 [deps] Dropped Django 1.11 and Python 3.5
  .travis.yml
  README.rst
  tox.ini
Labels: Clean up, enhancement
